trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - 'Resources/Utilities/ExportNuGetStatistics/*'
    - 'Resources/CI/stat-nuget.yaml'

pr: none

schedules:
- cron: '0 0 * * *'
  displayName: Export NuGet package statistics
  branches:
    include:
    - develop
  always: 'true'

pool:
  vmImage: 'windows-latest'

variables:
- group: DryWetMIDI-InfluxDB-Variables
- group: DryWetMIDI-Common-Variables

name: ExportNuGetStat_$(Rev:r)

steps:
- template: Templates/step-setup-framework.yaml
  parameters:
    framework: 'Net'
    
- task: DotNetCoreCLI@2
  displayName: 'Export NuGet package info to InfluxDB Cloud'
  inputs:
    command: 'run'
    projects: 'Resources/Utilities/ExportNuGetStatistics/ExportNuGetStatistics/ExportNuGetStatistics.csproj'
    arguments: '-c Release -- "$(InfluxDB.Url)" "$(InfluxDB.WriteToken)" "$(InfluxDB.Organization)" "$(InfluxDB.Bucket)" "$(InfluxDB.Measurement.NuGet)"'