trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - 'DryWetMidi/*'
    - 'Resources/CI/test-net-selfcontained-package-integration.yaml'
    - 'Resources/CI/Templates/stage-build-native-libs.yaml'
    - 'Resources/CI/Templates/step-create-ports-macos.yaml'
    - 'Resources/CI/Templates/step-create-ports-windows.yaml'
    - 'Resources/CI/Templates/job-build-package.yaml'
    - 'Resources/CI/Templates/step-setup-framework-variables.yaml'
    - 'Resources/PackageIntegrationTestUtilities/DwmNetSelfContainedConsoleApp/*'
    - 'Resources/Native/*'

pr: none

variables:
- group: DryWetMIDI-Common-Variables

name: TestPackageIntegration_NetSelfContained_$(SourceBranchName)_$(LibraryVersion)$(Rev:.r)

stages:
- template: Templates/stage-build-native-libs.yaml

- stage: BuildPackage
  displayName: Build package
  pool:
    vmImage: 'windows-latest'
  jobs:
  - template: Templates/job-build-package.yaml
    parameters:
      buildConfiguration: $(BuildConfiguration)
      packageType: 'Full'

- stage: TestPackageIntegration
  displayName: Test package integration
  jobs:
  - job: TestPackageIntegration
    displayName: Test package integration
    strategy:
      matrix:
        Windows_Net_IncludeAll:
          vmImage: 'windows-2019'
          rid: 'win-x64'
          includeAll: 'true'
        macOS_Net_IncludeAll:
          vmImage: 'macos-latest'
          rid: 'osx-x64'
          includeAll: 'true'
        Windows_Net_DontIncludeAll:
          vmImage: 'windows-2019'
          rid: 'win-x64'
          includeAll: 'false'
        macOS_Net_DontIncludeAll:
          vmImage: 'macos-latest'
          rid: 'osx-x64'
          includeAll: 'false'
    pool:
      vmImage: $(vmImage)
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download NuGet package
      inputs:
        source: 'current'
        path: '$(Pipeline.Workspace)\NuGetPackage'
        artifact: NuGetPackage
    
    - template: Templates/step-setup-framework.yaml
      parameters:
        framework: 'Net'
    
    - template: Templates/step-create-ports-windows.yaml
      parameters:
        enabled: contains(variables.vmImage, 'windows')
        
    - template: Templates/step-create-ports-macos.yaml
      parameters:
        enabled: contains(variables.vmImage, 'macos')
    
    - task: PowerShell@2
      displayName: Restore NuGet packages
      inputs:
        targetType: 'inline'
        script: |
          $path = Resolve-Path 'Resources\PackageIntegrationTestUtilities\DwmNetSelfContainedConsoleApp\DwmNetSelfContainedConsoleApp\DwmNetSelfContainedConsoleApp.csproj'
          dotnet restore "$path" -s "https://api.nuget.org/v3/index.json"
    
    - task: PowerShell@2
      displayName: Add package to the project
      inputs:
        targetType: 'inline'
        script: |
          $path = Resolve-Path 'Resources\PackageIntegrationTestUtilities\DwmNetSelfContainedConsoleApp\DwmNetSelfContainedConsoleApp\DwmNetSelfContainedConsoleApp.csproj'
          dotnet add "$path" package Melanchall.DryWetMidi -v $(LibraryVersion) -s "$(Pipeline.Workspace)\NuGetPackage"
          
    - task: PowerShell@2
      displayName: Set csproj elements
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Parsing csproj..."
          [xml]$xml = Get-Content -Path 'Resources\PackageIntegrationTestUtilities\DwmNetSelfContainedConsoleApp\DwmNetSelfContainedConsoleApp\DwmNetSelfContainedConsoleApp.csproj'
          
          Write-Host "Setting IncludeAllContentForSelfExtract to $(includeAll)..."
          $xml.Project.PropertyGroup.IncludeAllContentForSelfExtract = '$(includeAll)'
          
          Write-Host "Saving csproj..."
          $path = Resolve-Path 'Resources\PackageIntegrationTestUtilities\DwmNetSelfContainedConsoleApp\DwmNetSelfContainedConsoleApp\DwmNetSelfContainedConsoleApp.csproj'
          $xml.Save($path)
          
          Write-Host "Displaying csproj content..."
          $content = Get-Content -Path 'Resources\PackageIntegrationTestUtilities\DwmNetSelfContainedConsoleApp\DwmNetSelfContainedConsoleApp\DwmNetSelfContainedConsoleApp.csproj'
          Write-Host $content

    - task: PowerShell@2
      displayName: Restore packages
      inputs:
        targetType: 'inline'
        script: |
          $path = Resolve-Path 'Resources\PackageIntegrationTestUtilities\DwmNetSelfContainedConsoleApp\DwmNetSelfContainedConsoleApp\DwmNetSelfContainedConsoleApp.csproj'
          dotnet nuget add source "$(Pipeline.Workspace)\NuGetPackage"
          dotnet restore "$path"

    - task: PowerShell@2
      displayName: Publish test program executable
      inputs:
        targetType: 'inline'
        script: |
          $path = Resolve-Path 'Resources\PackageIntegrationTestUtilities\DwmNetSelfContainedConsoleApp\DwmNetSelfContainedConsoleApp\DwmNetSelfContainedConsoleApp.csproj'
          dotnet publish "$path" -c Release -r $(rid) -o "$(Pipeline.Workspace)\App"
          
    - task: PowerShell@2
      displayName: Run test program (Windows)
      condition: contains(variables.vmImage, 'windows')
      inputs:
        targetType: 'inline'
        script: |
          $exePath = Get-ChildItem -Path "$(Pipeline.Workspace)\App" -File -Filter "DwmNetSelfContainedConsoleApp.exe" -Recurse
          & $exePath.FullName
          
    - task: PowerShell@2
      displayName: Run test program (macOS)
      condition: contains(variables.vmImage, 'macos')
      inputs:
        targetType: 'inline'
        script: |
          $exePath = Get-ChildItem -Path "$(Pipeline.Workspace)\App" -File -Filter "DwmNetSelfContainedConsoleApp" -Recurse
          & $exePath.FullName